[package]
name = "meshmeshmesh"
version = "0.1.5"
edition = "2021"
authors = ["Wojciech Radaczyński"]
description = "Open-source mesh processing library."
repository = "https://github.com/paireks/meshmeshmesh"
license = "AGPL-3.0-only"
readme = "README.md"
categories = ["algorithms"]
keywords = ["mesh", "geometry"]
exclude = [
    ".idea",
    "models"
]

[dependencies]
dotbim_rust = "0.1.1"
serde = { version = "1.0.205", features = ["derive"] }
serde_json = "1.0"
